/**
 * Генератор public/sitemap.xml.
 *
 * Зачем скрипт вместо файла руками: карта — это (страницы × языки) записей, и в каждой
 * полный hreflang-набор, ссылающийся на все версии, включая себя. На двух языках это
 * было 28 записей, на трёх — 42, и каждая новая страница требовала правок в четырёх
 * местах. Ручная синхронизация уже подводила: Bing три недели обходил карту из 24 URL,
 * когда на сайте их было 28.
 *
 * Источник правды — PAGES ниже. Держать в синхроне с PAGES в src/App.jsx и
 * scripts/prerender.js (этот скрипт запускается в Node и модули приложения
 * импортировать не может).
 *
 * Запускается в составе `npm run build` перед prerender: карта попадает в dist через
 * public/, поэтому файл пишется именно в public/, а не в dist/.
 */
import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE_URL = 'https://levelup-academy.uz';

/** Русский — без префикса (его URL уже проиндексированы), остальные языки — с ним. */
const DEFAULT_LANG = 'ru';
const PREFIXED_LANGS = ['uz', 'en'];
const LANGS = [DEFAULT_LANG, ...PREFIXED_LANGS];

/** Куда ведёт x-default — версия для тех, чей язык не совпал ни с одним объявленным. */
const X_DEFAULT_LANG = 'en';

/**
 * Канонические пути и их метаданные.
 * `lastmod` правится вручную при изменении контента страницы: проставлять дату сборки
 * всем URL подряд — значит каждый раз сообщать поисковику, что обновился весь сайт.
 */
const PAGES = [
  { path: '/landing', lastmod: '2026-08-05', changefreq: 'weekly', priority: '1.0' },
  { path: '/landing/features', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.9' },
  { path: '/landing/pricing', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.9' },
  { path: '/landing/finance', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/for-language-school', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/for-courses', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/crm-vs-excel', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/vs/modme', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/vs/umai', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/roles', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.7' },
  { path: '/landing/gamification', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.7' },
  { path: '/landing/blog', lastmod: '2026-08-05', changefreq: 'weekly', priority: '0.7' },
  { path: '/landing/blog/excel-to-crm', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.6' },
  { path: '/landing/blog/student-debts', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.6' },
  { path: '/landing/blog/attendance-automation', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.6' },
  { path: '/landing/faq', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.8' },
  { path: '/landing/about', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.6' },
  { path: '/landing/team', lastmod: '2026-08-24', changefreq: 'monthly', priority: '0.7' },
  {
    path: '/landing/team/azizbek-amangeldiev',
    lastmod: '2026-08-20',
    changefreq: 'monthly',
    priority: '0.6',
  },
  { path: '/landing/team/yunusov-abdulloh', lastmod: '2026-08-24', changefreq: 'monthly', priority: '0.6' },
  { path: '/landing/contacts', lastmod: '2026-08-05', changefreq: 'monthly', priority: '0.6' },
];

const localizePath = (path, lang) => (lang === DEFAULT_LANG ? path : `/${lang}${path}`);
const urlFor = (path, lang) => `${SITE_URL}${localizePath(path, lang)}`;

function urlEntry({ path, lastmod, changefreq, priority }, lang) {
  const alternates = [
    ...LANGS.map((l) => `      <xhtml:link rel="alternate" hreflang="${l}" href="${urlFor(path, l)}" />`),
    `      <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor(path, X_DEFAULT_LANG)}" />`,
  ].join('\n');

  return `  <url>
    <loc>${urlFor(path, lang)}</loc>
${alternates}
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

const body = LANGS.flatMap((lang) => [
  `  <!-- ===================== ${lang.toUpperCase()} ===================== -->`,
  ...PAGES.map((page) => urlEntry(page, lang)),
]).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
<!--
  GENERATED by scripts/sitemap.js — do not edit by hand, run \`npm run sitemap\`.

  Canonical URLs only. The site root (/) is a 308 redirect to /landing and is
  deliberately absent: a sitemap lists destinations, not redirects.

  Every URL declares the full hreflang set (every language plus x-default), including a
  link to itself — Google ignores the whole cluster if the references are not reciprocal.
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${body}
</urlset>
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml');
await writeFile(out, xml, 'utf-8');
console.log(`  ✓ sitemap.xml → ${PAGES.length} pages × ${LANGS.length} langs = ${PAGES.length * LANGS.length} URLs`);
